obs_dict1={
    'default':'',
    'Questions 1 and 2':"<b>Question 1</b>: A priori, it is very dificult to hipothesize about the main drivers that students take into acount when deciding a career, also, we have to make sure that the client can <b>influence</b> those variables, for example, if we determine that the students go on a specific career path due to their parents paths, that information wouldn't be usefull at all since the client cannot do anything about it. So taking that out of the picture, lets start with the <b>'in the box'</b> thinking, price, marketing, trade and distribution are the usual old boring variables that permeate through businesses, so the classic CPG study on those variables is fundamental. For example, maybe just decreasing the price, or adjusting the price student is more usefull that one might think at first glance. There are infinite ways of changing prices, for example, a <b>scholarship system</b> is just a consumer discrimination price strategy. Regarding marketing, focusing on the <b>university rankings</b> is crucial for the consumer choice. \n Now come the 'out of the box' hipothesis, brainstorming requires more people, but maybe an idea would be to open <b>new careers</b>. \n\n  Now that we recognize all the possible levers, the information must be scraped in order to correctly actionize on them; following the previous examples we would collect <b>time series</b> of our and our competitors investment in marketing and rankings, geographical distribution, prices, percent of scholarships types of careers available will be important, obviously, there will be an increasing quantity of ideas from what to collect, but this should be a good starting point, <b>understand the market</b>.",
    'Question 4': "<b>Question 4</b>: Lets inquire in the previous 2 selected variables. Notice that having a 'None' answer is a good predictor for switching unis, <b>BUT</b> here we have to be extra extra carefull since NaN values tend to be very dubious and to produce <b>data leakeage</b>. A first naive conclusion is that people that dont know what to do next will go out of the passthrough process; however, maybe some of the 'None' answers are from students that just <b>didn't answer</b> the survey and automatically are clasified as 'other university', due to time isues i will not go in deep into this problem. "
}
obs_dict2={
    'default':'',
    'Questions 1 and 2':"<b>Question 2</b>: The main available columns to take into account will be 'Institucion', 'Año', 'Curso', 'Probabilidad UIN', 'Carrera 1', 'Carrera 2', 'Carrera 3', 'Universidad 1', 'Universidad 2', 'Universidad 3'. The columns that we want to influence are 'Universidad 1', 'Universidad 2', 'Universidad 3', 'Probabilidad UIN', so the <b>KPIs</b> will be constructed from these columns, for simplification, i just used 1 KPI that being a dummy variable that is 1 when the 'Universidad 1' column is UNAM or UIN (i just asumed that the client is owner of these 2 universities) and 0 if it is other value. Now we want to understand how the other columns influence our KPI, first i preprocessed a little bit the other columns, using the <b>openai api</b>, i detected the probable gender of the students from their name, and clustered the 'Carrera 1' column so that it is more understandable, i once again dropped 'Carrera 2' and 'Carrera 3' due to time considerations for simplification. Intersecting <b>vizualizations and predictive models</b> is the best way to deeply understand how the underliying data affects the KPIs. Putting all the relevant variables, we can calculate a regularized logistic regression, it will take some time to fit the regression, but after 1 minute more or less, at the <b>end of the page</b> we will get that the main 2 variables that influence the decision are <b>'Año'</b> and <b>'Carrera 1 Clustered'</b>, so we will put the first focus there.",
    'Question 4': "Now i will enumerate possible insights with their recomendations from the full model: \n\n 1. Being in <b>sixth year</b> makes people more probable to stay: this may be due to students taking their desicions more seriously in<br>the last year, so the marketing directed at them should be more <b>straight foward</b> while the marketing for previous years a little<br>bit more subtle. \n\n 2. Not having a career selected makes people more probable to not stay: a straight foward solution, is to just <b>help</b> a lot the students<br>find a career that they like, and naturally more people will stay. \n\n 3. People that look for <b>Social Sciences</b> or <b>STEM</b>  are more probable to stay: this may require a better study on the key attractors<br>from these 2 disciplines, but for a short term solution, investing better <b>human capital</b> (teachers) for the early stages in<br>these 2 subjects will get more students interested in this funnel.  \n\n 4. The <b>Tlalpan</b>, <b>Sur2</b> and <b>Chalco</b> Regions have a slight edge keeping students: Here we have other possible further study, with<br>other short term decision, fund more those regions since their <b>ROIs</b> are better. \n\n 5. <b>UNAM</b> keeps more students that UIN: Lastly, i supposed (maybe incorrectly) that UNAM is from the same group, due to time limits<br>i will not give a recommendation, but further study might be critical."
   
}
   
